import React from 'react';
import { 
  DollarSign, 
  ShieldCheck, 
  Sparkles, 
  HelpCircle, 
  Video, 
  Lock, 
  CheckCircle2, 
  ArrowLeft,
  Tv,
  Calendar,
  Wallet,
  TrendingUp,
  Award
} from 'lucide-react';
import { Language } from '../locales/i18n';

interface CreatorProgramViewProps {
  language: Language;
  onNavigateHome: () => void;
  onOpenPolicies?: (tab: string) => void;
  theme?: 'dark' | 'light';
}

export const CreatorProgramView: React.FC<CreatorProgramViewProps> = ({
  language,
  onNavigateHome,
  onOpenPolicies,
  theme = 'dark'
}) => {
  const isHi = language === 'hi';
  const isLight = theme === 'light';

  return (
    <div className="max-w-5xl mx-auto py-6 px-3 sm:px-6 space-y-8 animate-fadeIn">
      {/* Top Breadcrumb & Back */}
      <div className="flex items-center justify-between gap-4 pb-4 border-b border-slate-200 dark:border-slate-800">
        <button
          onClick={onNavigateHome}
          className="inline-flex items-center gap-2 text-xs font-semibold text-slate-600 dark:text-slate-400 hover:text-amber-500 transition cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>{isHi ? 'मुख्य पृष्ठ पर वापस जाएं' : 'Back to Home'}</span>
        </button>

        <div className="flex items-center gap-2">
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-amber-500/10 text-amber-500 border border-amber-500/30">
            <DollarSign className="w-3.5 h-3.5" />
            50% Creator Revenue Share
          </span>
        </div>
      </div>

      {/* Main Header Banner */}
      <div className="relative overflow-hidden rounded-3xl p-6 sm:p-10 bg-gradient-to-br from-emerald-500/15 via-slate-900 to-slate-950 border border-emerald-500/20 shadow-2xl">
        <div className="relative z-10 space-y-4 max-w-3xl">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
            <Sparkles className="w-3.5 h-3.5" />
            <span>{isHi ? 'बुन्देली क्रिएटर पार्टनरशिप प्रोग्राम' : 'BundeliTube Creator Partner Program'}</span>
          </div>
          <h1 className="text-2xl sm:text-4xl font-black text-slate-100 tracking-tight leading-tight">
            {isHi 
              ? '50/50 रेवेन्यू शेयरिंग: अपनी कला और वीडियो से कमाएं असली पैसा' 
              : '50/50 Revenue Sharing: Monetize Folk Art & Video Content'}
          </h1>
          <p className="text-sm sm:text-base text-slate-300 leading-relaxed">
            {isHi
              ? 'बुन्देलीट्यूब पर प्रत्येक क्रिएटर के वीडियो पर आने वाले विज्ञापनों की 50% शुद्ध कमाई सीधे क्रिएटर के खाते में जाती है। न कोई छुपा हुआ शुल्क, न कोई मध्यस्थ—पूरी पारदर्शिता के साथ हर महीने समय पर भुगतान।'
              : 'Every creator receives a transparent 50% net share of all verified Google AdSense and AdMob ad impressions generated by their video content. Timely monthly payouts directly to Bank or UPI.'}
          </p>
        </div>
      </div>

      {/* 3 Step Workflow */}
      <div className="space-y-4">
        <h2 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
          <TrendingUp className="w-5 h-5 text-amber-500" />
          <span>{isHi ? 'यह कैसे काम करता है? (3 सरल चरण)' : 'How It Works (3 Simple Steps)'}</span>
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className={`p-5 rounded-2xl border ${isLight ? 'bg-white border-slate-200' : 'bg-slate-900/60 border-slate-800'} space-y-2`}>
            <div className="w-9 h-9 rounded-xl bg-amber-500/10 text-amber-500 flex items-center justify-center font-black text-sm border border-amber-500/20">
              1
            </div>
            <h4 className="font-bold text-sm text-slate-900 dark:text-slate-100">
              {isHi ? 'चैनल बनाएं व वीडियो सबमिट करें' : 'Create Channel & Upload'}
            </h4>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
              {isHi
                ? 'मुफ्त में चैनल रजिस्टर करें और अपना यूट्यूब वीडियो लिंक या डायरेक्ट वीडियो अपलोड करें। आपको ओनरशिप वेरिफिकेशन कोड (BT-Code) प्राप्त होगा।'
                : 'Free channel registration. Submit YouTube link or direct video. Receive unique BT verification code for ownership.'}
            </p>
          </div>

          <div className={`p-5 rounded-2xl border ${isLight ? 'bg-white border-slate-200' : 'bg-slate-900/60 border-slate-800'} space-y-2`}>
            <div className="w-9 h-9 rounded-xl bg-blue-500/10 text-blue-500 flex items-center justify-center font-black text-sm border border-blue-500/20">
              2
            </div>
            <h4 className="font-bold text-sm text-slate-900 dark:text-slate-100">
              {isHi ? 'एडमिन समीक्षा व अप्रूवल' : 'Admin Pre-Moderation'}
            </h4>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
              {isHi
                ? 'वीडियो पहले सुरक्षित पेंडिंग डेटाबेस में रहता है। एडमिन पैनल से कॉपीराइट और गुणवत्ता की जांच के बाद वीडियो मुख्य पेज पर लाइव होता है।'
                : 'Content is isolated in pending queue. Editorial review ensures originality and ad safety before going live on the home feed.'}
            </p>
          </div>

          <div className={`p-5 rounded-2xl border ${isLight ? 'bg-white border-slate-200' : 'bg-slate-900/60 border-slate-800'} space-y-2`}>
            <div className="w-9 h-9 rounded-xl bg-emerald-500/10 text-emerald-500 flex items-center justify-center font-black text-sm border border-emerald-500/20">
              3
            </div>
            <h4 className="font-bold text-sm text-emerald-600 dark:text-emerald-400">
              {isHi ? '50% कमाई व मासिक भुगतान' : '50% Earnings & Payout'}
            </h4>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
              {isHi
                ? 'वीडियो पर दर्शक विज्ञापन देखते हैं। हर वैध विज्ञापन का 50% रेवेन्यू वॉलेट में जुड़ता है और 1 से 6 तारीख के बीच बैंक या UPI में विड्रॉल मिलता है।'
                : 'Genuine views trigger verified ad revenue. 50% is credited to your wallet and paid out during monthly withdrawal window.'}
            </p>
          </div>
        </div>
      </div>

      {/* Payout & Withdrawal Window Box */}
      <div className={`p-6 rounded-2xl border ${isLight ? 'bg-amber-50/60 border-amber-200' : 'bg-slate-900/80 border-amber-500/30'} space-y-3`}>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-amber-500/20 text-amber-500 flex items-center justify-center shrink-0">
            <Calendar className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-base text-slate-900 dark:text-slate-100">
              {isHi ? 'निकासी चक्र (Payout Window): महीने की 1 से 6 तारीख' : 'Monthly Withdrawal Window: 1st to 6th of Every Month'}
            </h3>
            <p className="text-xs text-slate-600 dark:text-slate-300">
              {isHi
                ? 'वित्तीय नियमों और Google AdSense पेआउट साइकिल के अनुसार निकासी विंडो हर महीने 1 तारीख से 6 तारीख तक खुली रहती है।'
                : 'In alignment with banking settlements and ad verification, withdrawals open between the 1st and 6th of each calendar month.'}
            </p>
          </div>
        </div>
      </div>

      {/* Frequently Asked Questions */}
      <div className={`p-6 rounded-2xl border ${isLight ? 'bg-white border-slate-200' : 'bg-slate-900/60 border-slate-800'} space-y-4`}>
        <h3 className="font-bold text-base text-slate-900 dark:text-slate-100 flex items-center gap-2">
          <HelpCircle className="w-4 h-4 text-amber-500" />
          <span>{isHi ? 'क्रिएटर अक्सर पूछे जाने वाले सवाल (FAQ)' : 'Frequently Asked Questions'}</span>
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-1">
            <p className="font-bold text-slate-900 dark:text-slate-100">
              {isHi ? 'Q. क्या चैनल बनाने या वीडियो अपलोड करने की कोई फ़ीस है?' : 'Q. Is there any fee to create a channel?'}
            </p>
            <p className="text-slate-600 dark:text-slate-400 text-[11px] leading-relaxed">
              {isHi 
                ? 'बिल्कुल नहीं! बुन्देलीट्यूब पर रजिस्ट्रेशन और वीडियो अपलोड 100% मुफ़्त है।' 
                : 'Never! Registering your channel and uploading videos is 100% free forever.'}
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-1">
            <p className="font-bold text-slate-900 dark:text-slate-100">
              {isHi ? 'Q. न्यूनतम विड्रॉल सीमा क्या है?' : 'Q. What is the minimum withdrawal threshold?'}
            </p>
            <p className="text-slate-600 dark:text-slate-400 text-[11px] leading-relaxed">
              {isHi 
                ? 'क्रिएटर के वॉलेट में न्यूनतम सीमा पूरी होते ही विड्रॉल रिक्वेस्ट भेजी जा सकती है।' 
                : 'Payouts can be requested once your wallet reaches the minimum withdrawal threshold.'}
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-1">
            <p className="font-bold text-slate-900 dark:text-slate-100">
              {isHi ? 'Q. अमान्य क्लिक और धोखाधड़ी नीति क्या है?' : 'Q. What is the anti-fraud policy?'}
            </p>
            <p className="text-slate-600 dark:text-slate-400 text-[11px] leading-relaxed">
              {isHi 
                ? 'स्वयं के विज्ञापनों पर क्लिक करना या बॉट ट्रैफ़िक लाना सख्त वर्जित है। ऐसा करने पर चैनल ब्लॉक हो सकता है।' 
                : 'Self-clicking or generating bot impressions results in immediate channel suspension and forfeiture.'}
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-1">
            <p className="font-bold text-slate-900 dark:text-slate-100">
              {isHi ? 'Q. सहायता व सपोर्ट कहाँ मिलेगा?' : 'Q. How to get creator support?'}
            </p>
            <p className="text-slate-600 dark:text-slate-400 text-[11px] leading-relaxed">
              {isHi 
                ? 'ईमेल: sanjaykushwaha975297@gmail.com अथवा हेल्प सेंटर से सीधे संपर्क कर सकते हैं।' 
                : 'Contact via email: sanjaykushwaha975297@gmail.com or access the in-app Help Center.'}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
